# Generated by Django 4.1.7 on 2023-02-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshopapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='author',
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='White', max_length=255),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_consumption',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='max_speed',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='car',
            name='overclocking',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='car',
            name='power',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, default='6', upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(default='Car', max_length=255),
        ),
        migrations.AlterField(
            model_name='description',
            name='author',
            field=models.CharField(default='User', max_length=255),
        ),
    ]
